run:
  timeout: 10m
    
linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - whitespace

linters-settings:
  funlen:
    lines: 100
    statements: 60
  lll:
    line-length: 200

