// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/decks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carddeck"
                ],
                "summary": "Create new deck",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Specify whether newly created deck is shuffled or not",
                        "name": "shuffled",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Specify cards used in this newly created deck",
                        "name": "cards",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/decks/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carddeck"
                ],
                "summary": "\"Open\" a new deck, or get deck by specific ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the deck",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/decks/{id}/cards": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carddeck"
                ],
                "summary": "Draw cards from specific deck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the deck",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of cards to withdraw",
                        "name": "count",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
